### ISSUE TITLE
Interrupt for Win terminal not returning prompt

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/minorminer#128]
**Description**
Trying to interrupt an embedding in a Windows terminal under an ipython interpreter acknowledges 
the interrupt but does not return control to user:
```
In [28]: import minorminer
    ...: minorminer.find_embedding(Q.keys(), sampler.edgelist)
caught interrupt; embedding cancelled
caught interrupt; embedding cancelled
caught interrupt; embedding cancelled                                                                                                                             
```

**To Reproduce**
I'm running `find_embedding(Q.keys(), sampler.edgelist)` where `Q` is 500 nodes highly connected (about 50% of a clique) and `sampler` is the `DW_2000Q_6`. (Low expectations of success, I wanted the error message)

**Expected behavior**
CNTR-C should return prompt to user.

**Environment:**
 - OS: WIN 10 terminal
 - Python version: ipython 3.6.5

**Additional context**

**Comment by boothby** [comment]
This is fixed in the current version, will be included in the next release.

See #117 for more info:

https://github.com/dwavesystems/minorminer/pull/117/commits/41217eeda6002ca419a71c40d68824345a6e31f4

In the meantime, you can set `tries = 1`, and the first time you hit ctrl-c and it'll bail more or less immediately.

**Comment by JoelPasvolsky** [comment]
Thank you!
